### ISSUE TITLE
Compiling regex expressions (Day5)

### ISSUE THREAD

**Issue by johnroach** [mpirnat/adventofcode#1]
I think it might be beneficial to use [re.compile()](https://docs.python.org/3/library/re.html#re.compile). Looked for you in the leadership board!

**Comment by mpirnat** [comment]
I missed the leaderboard by about a minute or so. Got fouled up on one of
the regexes for a couple minutes.

re.compile can be useful for sure but processing time didn't really matter
here. If I were writing that for production, where shaving off CPU time has
a business impact, I'd probably have used it. But this isn't, so I didn't.
:-)

On Sat, Dec 5, 2015 at 10:36 PM, John Roach notifications@github.com
wrote:

> I think it might be beneficial to use re.compile()
> https://docs.python.org/3/library/re.html#re.compile. Looked for you in
> the leadership board!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mpirnat/adventofcode/issues/1.

## 

Mike Pirnat
mpirnat@gmail.com
http://mike.pirnat.com/

**Comment by mpirnat** [comment]
I like your implementation a lot better than mine. Well done!

On Sat, Dec 5, 2015 at 11:56 PM, Mike Pirnat mpirnat@gmail.com wrote:

> I missed the leaderboard by about a minute or so. Got fouled up on one of
> the regexes for a couple minutes.
> 
> re.compile can be useful for sure but processing time didn't really matter
> here. If I were writing that for production, where shaving off CPU time has
> a business impact, I'd probably have used it. But this isn't, so I didn't.
> :-)
> 
> On Sat, Dec 5, 2015 at 10:36 PM, John Roach notifications@github.com
> wrote:
> 
> > I think it might be beneficial to use re.compile()
> > https://docs.python.org/3/library/re.html#re.compile. Looked for you
> > in the leadership board!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mpirnat/adventofcode/issues/1.
> 
> ## 
> 
> Mike Pirnat
> mpirnat@gmail.com
> http://mike.pirnat.com/

## 

Mike Pirnat
mpirnat@gmail.com
http://mike.pirnat.com/

**Comment by johnroach** [comment]
Meh. I think your TDD approach is more awesome. I tried to make it in the list this time but failed :( maybe next time.
